##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##

robot_cfg:
  kinematics:
    usd_path: "robot/debug3.usd"
    usd_robot_root: "/robot"
    isaac_usd_path: ""
    usd_flip_joints: {}
    usd_flip_joint_limits: []

    urdf_path: "robot/debug3.urdf"
    asset_root_path: "robot"
    
    base_link: "panda_link0"
    ee_link: "panda_link8"
    link_names: null
    lock_joints: null
    extra_links: {"attached_object":{"parent_link_name": "panda_link8" ,
    "link_name": "attached_object", "fixed_transform": [0,0,0,1,0,0,0], "joint_type":"FIXED",
    "joint_name": "attach_joint" }}

    
    collision_link_names: 
      [
        "panda_link0",
        "panda_link1",
        "panda_link2",
        "panda_link3",
        "panda_link4",
        "panda_link5",
        "panda_link6",
        "panda_link7",
        "mount_4",
        "robotiq_85_base_link",
        "left_outer_finger",
        "right_outer_finger",
        "left_inner_finger",
        "right_inner_finger",
        "attached_object",
      ] # List[str]
    collision_spheres:
      panda_link0:
          - "center": [0.0, 0.0, 0.085]
            "radius": 0.03 #0.07
          - "center": [-0.1, -0.0, 0.085]
            "radius": 0.03 #0.07
      panda_link1:
          - "center": [0.0, -0.08, 0.0]
            "radius": 0.055
          - "center": [0.0, -0.03, 0.0]
            "radius": 0.06
          - "center": [0.0, 0.0, -0.12]
            "radius": 0.06
          - "center": [0.0, 0.0, -0.17]
            "radius": 0.06
      panda_link2:
          - "center": [0.0, 0.0, 0.03]
            "radius": 0.055
          - "center": [0.0, 0.0, 0.08]
            "radius": 0.055
          - "center": [0.0, -0.12, 0.0]
            "radius": 0.055
          - "center": [0.0, -0.17, 0.0]
            "radius": 0.055
      panda_link3:
          - "center": [0.0, 0.0, -0.06]
            "radius": 0.05
          - "center": [0.0, 0.0, -0.1]
            "radius": 0.06
          - "center": [0.08, 0.06, 0.0]
            "radius": 0.052
          - "center": [0.08, 0.02, 0.0]
            "radius": 0.052
      panda_link4:
          - "center": [0.0, 0.0, 0.02]
            "radius": 0.052
          - "center": [0.0, 0.0, 0.06]
            "radius": 0.052
          - "center": [-0.08, 0.095, 0.0]
            "radius": 0.055
          - "center": [-0.08, 0.06, 0.0]
            "radius": 0.052
      panda_link5:
          - "center": [0.0, 0.03, 0.0]
            "radius": 0.05
          - "center": [0.0, 0.082, 0.0]
            "radius": 0.05
          - "center": [0.0, 0.000, -0.22]
            "radius": 0.05
          - "center": [0.0, 0.052, -0.18]
            "radius": 0.04
          - "center": [0.01, 0.08, -0.14]
            "radius": 0.022
          - "center": [0.01, 0.085, -0.11]
            "radius": 0.022
          - "center": [0.01, 0.09, -0.08]
            "radius": 0.022
          - "center": [0.01, 0.095, -0.05]
            "radius": 0.022
          - "center": [-0.01, 0.08, -0.14]
            "radius": 0.022
          - "center": [-0.01, 0.085, -0.11]
            "radius": 0.022
          - "center": [-0.01, 0.09, -0.08]
            "radius": 0.022
          - "center": [-0.01, 0.095, -0.05]
            "radius": 0.022
          - "center": [0.0, -0.009, 0.0]
            "radius": 0.05
      panda_link6:
          - "center": [0.085, 0.035, 0.0]
            "radius": 0.045 
          - "center": [0.085, 0.0, 0.0]
            "radius": 0.045 
          - "center": [0.085, -0.015, 0.0]
            "radius": 0.045 
      panda_link7:
          - "center": [0.0, 0.0, 0.07]
            "radius": 0.045
          - "center": [0.02, 0.04, 0.08]
            "radius": 0.024
          - "center": [0.04, 0.02, 0.08]
            "radius": 0.024
          - "center": [0.04, 0.06, 0.085]
            "radius": 0.02
          - "center": [0.06, 0.04, 0.085]
            "radius": 0.02
      mount_4:
          - "center": [0.08, 0.0, 0.0]
            "radius": 0.008
      robotiq_85_base_link:
          - "center": [0.0, -0.0, 0.04]
            "radius": 0.04
      left_outer_finger:
          - "center": [0.0, -0.01, 0.02]
            "radius": 0.03
      right_outer_finger:
          - "center": [0.0, -0.01, 0.02]
            "radius": 0.03
      right_inner_finger:
          - "center": [-0.005, 0.0, 0.02]
            "radius": 0.01
      left_inner_finger:
          - "center": [-0.005, 0.0, 0.02]
            "radius": 0.01

    collision_sphere_buffer: 0.004 # 0.0025
    extra_collision_spheres: {"attached_object": 100}
    self_collision_ignore: 
      {
        "panda_link0": ["panda_link1", "panda_link2"],
        "panda_link1": ["panda_link2", "panda_link3", "panda_link4"],
        "panda_link2": ["panda_link3", "panda_link4"],
        "panda_link3": ["panda_link4", "panda_link6"],
        "panda_link4": ["panda_link5", "panda_link6", "panda_link7", "panda_link8"],
        "panda_link5": ["panda_link6", "panda_link7", "mount_4", "robotiq_85_base_link", "left_outer_finger", "right_outer_finger", "left_inner_finger", "right_inner_finger", "attached_object"],
        "panda_link6": ["panda_link7", "mount_4", "robotiq_85_base_link", "left_outer_finger", "right_outer_finger", "left_inner_finger", "right_inner_finger", "attached_object"],
        "panda_link7": ["mount_4", "robotiq_85_base_link", "left_outer_finger", "right_outer_finger", "left_inner_finger", "right_inner_finger", "attached_object"],
        "mount_4": ["robotiq_85_base_link", "left_outer_finger", "right_outer_finger", "left_inner_finger", "right_inner_finger", "attached_object"],
        "robotiq_85_base_link": ["left_outer_finger", "right_outer_finger", "left_inner_finger", "right_inner_finger", "attached_object"],
        "left_outer_finger": ["right_outer_finger", right_inner_finger", "left_inner_finger", "attached_object"],
        "right_outer_finger": ["right_inner_finger", "left_inner_finger", "attached_object"],
        "left_inner_finger": ["right_inner_finger", "attached_object"],
        "right_inner_finger": ["attached_object"],

      } # Dict[str, List[str]]
    self_collision_buffer: 
      {
          "panda_link0": 0.1,
          "panda_link1": 0.05,
          "panda_link2": 0.0,
          "panda_link3": 0.0,
          "panda_link4": 0.0,
          "panda_link5": 0.0,
          "panda_link6": 0.0,
          "panda_link7": 0.0,
          "mount_4": 0.0,
          "robotiq_85_base_link": 0.02,
          "left_outer_finger": 0.0,
          "right_outer_finger": 0.0,
          "left_inner_finger": 0.01,
          "right_inner_finger": 0.01,
          "attached_object": 0.0,
        } # Dict[str, float]

    use_global_cumul: True
    mesh_link_names: 
      [
          "panda_link0",
          "panda_link1",
          "panda_link2",
          "panda_link3",
          "panda_link4",
          "panda_link5",
          "panda_link6",
          "panda_link7",
          "mount_4",
          "robotiq_85_base_link",
          "left_outer_knuckle",
          "left_outer_finger",
          "left_inner_knuckle",
          "left_inner_finger",
          "right_inner_knuckle",
          "right_inner_finger",
          "right_outer_knuckle",
          "right_outer_finger",
        ] # List[str]
    external_asset_path: null # Use this to add path for externally located assets/robot folder.
    lock_joints: {"finger_joint": 0.0}

    cspace:
      joint_names: ["panda_joint1","panda_joint2","panda_joint3","panda_joint4", "panda_joint5",
      "panda_joint6","panda_joint7", "finger_joint"] # List[str]
      retract_config: [0.0, -1.3, 0.0, -2.5, 0.0, 1.0, 0., 0.0] # List[float]
      null_space_weight: [1,1,1,1,1,1,1,1] # List[str]
      cspace_distance_weight: [1,1,1,1,1,1,1,1] # List[str]
      max_jerk: 500.0
      max_acceleration: 15.0
